"""initial schema baseline

Revision ID: 20260801_0001
Revises:
Create Date: 2026-08-01 12:00:00.606971
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa


revision: str = '20260801_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EXPECTED_TABLES = {
    'ai_image_analysis_jobs', 'categories', 'couple_goals', 'date_ideas',
    'families', 'family_join_requests', 'family_members',
    'google_calendar_connections', 'google_calendar_family_settings',
    'google_calendar_user_connections', 'image_assets', 'monthly_scores',
    'monthly_winners', 'notifications', 'quick_notes', 'task_assignees',
    'task_attachments', 'task_reminders', 'tasks', 'two_factor_codes',
    'users', 'web_push_subscriptions',
}
EXPECTED_AUTH_COLUMNS = {
    'users': {
        'active_family_id', 'ai_task_import_instructions', 'avatar_url',
        'created_at', 'email', 'email_task_reminders_enabled',
        'email_verified', 'email_verified_at', 'hashed_password', 'id',
        'is_active', 'last_2fa_verified_at', 'last_login_at', 'name',
        'push_task_reminders_enabled', 'token_version', 'two_factor_enabled',
        'updated_at', 'username',
    },
    'two_factor_codes': {
        'attempts', 'code_hash', 'consumed_at', 'created_at',
        'delivery_channel', 'expires_at', 'id', 'last_sent_at',
        'max_attempts', 'purpose', 'salt', 'updated_at', 'user_id',
    },
}
EXPECTED_USER_INDEXES = {
    'ix_users_email',
    'ix_users_username',
    'ix_users_username_lower_unique',
}


def _adopt_compatible_existing_schema() -> bool:
    if context.is_offline_mode():
        return False

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names()) - {'alembic_version'}
    if not existing_tables:
        return False

    missing_tables = EXPECTED_TABLES - existing_tables
    if missing_tables:
        raise RuntimeError(
            'Banco CasaSync parcial; tabelas ausentes antes da baseline: '
            + ', '.join(sorted(missing_tables))
        )

    for table_name, expected_columns in EXPECTED_AUTH_COLUMNS.items():
        actual_columns = {column['name'] for column in inspector.get_columns(table_name)}
        missing_columns = expected_columns - actual_columns
        if missing_columns:
            raise RuntimeError(
                f'Banco CasaSync incompativel; colunas ausentes em {table_name}: '
                + ', '.join(sorted(missing_columns))
            )

    user_indexes = {index['name'] for index in inspector.get_indexes('users')}
    expected_user_indexes = set(EXPECTED_USER_INDEXES)
    if bind.dialect.name == 'sqlite':
        expected_user_indexes.discard('ix_users_username_lower_unique')
    missing_indexes = expected_user_indexes - user_indexes
    if missing_indexes:
        raise RuntimeError(
            'Banco CasaSync incompativel; indices de autenticacao ausentes: '
            + ', '.join(sorted(missing_indexes))
        )
    return True


def upgrade() -> None:
    if _adopt_compatible_existing_schema():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_2fa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_task_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_task_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_task_import_instructions', sa.Text(), nullable=True),
    sa.Column('active_family_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_family_id'], ['families.id'], name='fk_users_active_family_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_active_family_id'), 'users', ['active_family_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(
        'ix_users_username_unique',
        'users',
        ['username'],
        unique=True,
        sqlite_where=sa.text('username IS NOT NULL'),
        postgresql_where=sa.text('username IS NOT NULL'),
    )
    op.create_index(
        'ix_users_username_lower_unique',
        'users',
        [sa.text('lower(username)')],
        unique=True,
        sqlite_where=sa.text('username IS NOT NULL'),
        postgresql_where=sa.text('username IS NOT NULL'),
    )
    op.create_table('families',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    if op.get_bind().dialect.name == 'postgresql':
        op.create_foreign_key(
            'fk_users_active_family_id',
            'users',
            'families',
            ['active_family_id'],
            ['id'],
            ondelete='SET NULL',
        )
    op.create_table('google_calendar_user_connections',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=4000), nullable=True),
    sa.Column('refresh_token_encrypted', sa.String(length=4000), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_scope', sa.String(length=1000), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_google_calendar_user_connection_user')
    )
    op.create_index('ix_google_calendar_user_connections_user_unique', 'google_calendar_user_connections', ['user_id'], unique=True)
    op.create_table('two_factor_codes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('delivery_channel', sa.String(length=24), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_two_factor_codes_expires_at', 'two_factor_codes', ['expires_at'], unique=False)
    op.create_index('ix_two_factor_codes_user_purpose', 'two_factor_codes', ['user_id', 'purpose'], unique=False)
    op.create_table('ai_image_analysis_jobs',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=240), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('suggestions_count', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('image_metadata_json', sa.Text(), nullable=True),
    sa.Column('image_errors_json', sa.Text(), nullable=True),
    sa.Column('image_context', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_image_analysis_jobs_family_id'), 'ai_image_analysis_jobs', ['family_id'], unique=False)
    op.create_index(op.f('ix_ai_image_analysis_jobs_status'), 'ai_image_analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_image_analysis_jobs_user_id'), 'ai_image_analysis_jobs', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'name', name='uq_category_family_name')
    )
    op.create_index('ix_categories_family_id', 'categories', ['family_id'], unique=False)
    op.create_table('couple_goals',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_ideas',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('budget', sa.String(length=80), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('suggested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mood', sa.String(length=60), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_join_requests',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_family_join_requests_pending_unique', 'family_join_requests', ['family_id', 'requester_id'], unique=True, sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.create_table('family_members',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('ai_aliases', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_member')
    )
    op.create_index('ix_family_members_family_id', 'family_members', ['family_id'], unique=False)
    op.create_index('ix_family_members_user_id', 'family_members', ['user_id'], unique=False)
    op.create_table('google_calendar_connections',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=4000), nullable=True),
    sa.Column('refresh_token_encrypted', sa.String(length=4000), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_scope', sa.String(length=1000), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_google_calendar_connection_family_user')
    )
    op.create_index('ix_google_calendar_connections_family_id', 'google_calendar_connections', ['family_id'], unique=False)
    op.create_index('ix_google_calendar_connections_user_id', 'google_calendar_connections', ['user_id'], unique=False)
    op.create_index(
        'ix_google_calendar_connections_family_user_unique',
        'google_calendar_connections',
        ['family_id', 'user_id'],
        unique=True,
        sqlite_where=sa.text('user_id IS NOT NULL'),
        postgresql_where=sa.text('user_id IS NOT NULL'),
    )
    op.create_table('google_calendar_family_settings',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_name', sa.String(length=180), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_google_calendar_family_settings')
    )
    op.create_index('ix_google_calendar_family_settings_family_id', 'google_calendar_family_settings', ['family_id'], unique=False)
    op.create_index('ix_google_calendar_family_settings_user_id', 'google_calendar_family_settings', ['user_id'], unique=False)
    op.create_index(
        'ix_google_calendar_family_settings_family_user_unique',
        'google_calendar_family_settings',
        ['family_id', 'user_id'],
        unique=True,
    )
    op.create_table('image_assets',
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('family_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_assets_family_id'), 'image_assets', ['family_id'], unique=False)
    op.create_index(op.f('ix_image_assets_owner_user_id'), 'image_assets', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_image_assets_scope'), 'image_assets', ['scope'], unique=False)
    op.create_table('monthly_scores',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', 'period_year', 'period_month', name='uq_monthly_score_period_user')
    )
    op.create_index('ix_monthly_scores_family_period', 'monthly_scores', ['family_id', 'period_year', 'period_month'], unique=False)
    op.create_table('monthly_winners',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('winner_user_id', sa.String(length=36), nullable=True),
    sa.Column('winner_name', sa.String(length=120), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'period_year', 'period_month', name='uq_monthly_winner_period')
    )
    op.create_index('ix_monthly_winners_family_period', 'monthly_winners', ['family_id', 'period_year', 'period_month'], unique=False)
    op.create_table('quick_notes',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_push_subscriptions',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_web_push_subscriptions_endpoint')
    )
    op.create_index(op.f('ix_web_push_subscriptions_family_id'), 'web_push_subscriptions', ['family_id'], unique=False)
    op.create_index(op.f('ix_web_push_subscriptions_is_active'), 'web_push_subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_web_push_subscriptions_user_id'), 'web_push_subscriptions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('task_type', sa.String(length=24), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_value', sa.Integer(), nullable=True),
    sa.Column('reminder_unit', sa.String(length=16), nullable=True),
    sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('google_calendar_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_calendar_synced_by_id', sa.String(length=36), nullable=True),
    sa.Column('automation_source', sa.String(length=80), nullable=True),
    sa.Column('automation_external_id', sa.String(length=160), nullable=True),
    sa.Column('automation_source_label', sa.String(length=180), nullable=True),
    sa.Column('automation_source_reference', sa.Text(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['google_calendar_synced_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_family_id', 'tasks', ['family_id'], unique=False)
    op.create_index('ix_tasks_google_calendar_event_id', 'tasks', ['google_calendar_event_id'], unique=False)
    op.create_index('ix_tasks_google_calendar_id', 'tasks', ['google_calendar_id'], unique=False)
    op.create_index(
        'ix_tasks_automation_external_unique',
        'tasks',
        ['family_id', 'automation_source', 'automation_external_id'],
        unique=True,
        sqlite_where=sa.text('automation_external_id IS NOT NULL'),
        postgresql_where=sa.text('automation_external_id IS NOT NULL'),
    )
    op.create_table('notifications',
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_status', sa.String(length=24), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_status', sa.String(length=24), nullable=False),
    sa.Column('push_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notifications_dedupe_key')
    )
    op.create_index(op.f('ix_notifications_dedupe_key'), 'notifications', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_notifications_family_id'), 'notifications', ['family_id'], unique=False)
    op.create_index(op.f('ix_notifications_task_id'), 'notifications', ['task_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('task_assignees',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_assignee')
    )
    op.create_table('task_attachments',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('original_name', sa.String(length=180), nullable=False),
    sa.Column('stored_name', sa.String(length=120), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attachments_family_id'), 'task_attachments', ['family_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_stored_name'), 'task_attachments', ['stored_name'], unique=True)
    op.create_index(op.f('ix_task_attachments_task_id'), 'task_attachments', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_uploaded_by_id'), 'task_attachments', ['uploaded_by_id'], unique=False)
    op.create_table('task_reminders',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'reminder_at', name='uq_task_reminder_at')
    )
    op.create_index(op.f('ix_task_reminders_family_id'), 'task_reminders', ['family_id'], unique=False)
    op.create_index(op.f('ix_task_reminders_reminder_at'), 'task_reminders', ['reminder_at'], unique=False)
    op.create_index(op.f('ix_task_reminders_sent'), 'task_reminders', ['sent'], unique=False)
    op.create_index(op.f('ix_task_reminders_task_id'), 'task_reminders', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_reminders_task_id'), table_name='task_reminders')
    op.drop_index(op.f('ix_task_reminders_sent'), table_name='task_reminders')
    op.drop_index(op.f('ix_task_reminders_reminder_at'), table_name='task_reminders')
    op.drop_index(op.f('ix_task_reminders_family_id'), table_name='task_reminders')
    op.drop_table('task_reminders')
    op.drop_index(op.f('ix_task_attachments_uploaded_by_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_task_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_stored_name'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_family_id'), table_name='task_attachments')
    op.drop_table('task_attachments')
    op.drop_table('task_assignees')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_task_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_family_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedupe_key'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_web_push_subscriptions_user_id'), table_name='web_push_subscriptions')
    op.drop_index(op.f('ix_web_push_subscriptions_is_active'), table_name='web_push_subscriptions')
    op.drop_index(op.f('ix_web_push_subscriptions_family_id'), table_name='web_push_subscriptions')
    op.drop_table('web_push_subscriptions')
    op.drop_table('quick_notes')
    op.drop_index('ix_monthly_winners_family_period', table_name='monthly_winners')
    op.drop_table('monthly_winners')
    op.drop_index('ix_monthly_scores_family_period', table_name='monthly_scores')
    op.drop_table('monthly_scores')
    op.drop_index(op.f('ix_image_assets_scope'), table_name='image_assets')
    op.drop_index(op.f('ix_image_assets_owner_user_id'), table_name='image_assets')
    op.drop_index(op.f('ix_image_assets_family_id'), table_name='image_assets')
    op.drop_table('image_assets')
    op.drop_table('google_calendar_family_settings')
    op.drop_table('google_calendar_connections')
    op.drop_table('family_members')
    op.drop_index('ix_family_join_requests_pending_unique', table_name='family_join_requests', sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('family_join_requests')
    op.drop_table('date_ideas')
    op.drop_table('couple_goals')
    op.drop_table('categories')
    op.drop_index(op.f('ix_ai_image_analysis_jobs_user_id'), table_name='ai_image_analysis_jobs')
    op.drop_index(op.f('ix_ai_image_analysis_jobs_status'), table_name='ai_image_analysis_jobs')
    op.drop_index(op.f('ix_ai_image_analysis_jobs_family_id'), table_name='ai_image_analysis_jobs')
    op.drop_table('ai_image_analysis_jobs')
    op.drop_index('ix_two_factor_codes_user_purpose', table_name='two_factor_codes')
    op.drop_index('ix_two_factor_codes_expires_at', table_name='two_factor_codes')
    op.drop_table('two_factor_codes')
    op.drop_table('google_calendar_user_connections')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    if op.get_bind().dialect.name == 'postgresql':
        op.drop_constraint('fk_users_active_family_id', 'users', type_='foreignkey')
    op.drop_table('families')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_active_family_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
